spring.application.name=orm-learn
logging.level.org.springframework=info
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.datasource.url=jdbc:h2:mem:ormlearn;MODE=MySQL;DATABASE_TO_UPPER=false
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=false
spring.h2.console.enabled=true
